{% set name = "pysnmp" %}
{% set version = "7.1.22" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://github.com/lextudio/{{ name }}/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 6bda6ac80d65fac77fd40f259405fc066b4218a616bf16b4345b3e98ca70feeb

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv --no-build-isolation
  skip: true  # [py<310]

requirements:
  host:
    - pip
    - python
    - flit-core>=3.9.0
  run:
    - python
    - pyasn1 >=0.4.8,!=0.5.0

# Tests disabled until a new version of pysmi is released.
# Latest pysmi in main 1.5.9, needs version >=1.6.1
test:
  imports:
    - pysnmp
    - pysnmp.carrier
    - pysnmp.carrier.asyncio
    - pysnmp.carrier.asyncio.dgram
    - pysnmp.entity
    - pysnmp.entity.rfc3413
    - pysnmp.hlapi.asyncio
    - pysnmp.proto
    - pysnmp.proto.acmod
    - pysnmp.proto.api
    - pysnmp.proto.mpmod
    - pysnmp.proto.proxy
    - pysnmp.proto.secmod
    - pysnmp.proto.secmod.eso
    - pysnmp.proto.secmod.eso.priv
    - pysnmp.proto.secmod.rfc3414
    - pysnmp.proto.secmod.rfc3414.auth
    - pysnmp.proto.secmod.rfc3414.priv
    - pysnmp.proto.secmod.rfc3826
    - pysnmp.proto.secmod.rfc3826.priv
    - pysnmp.proto.secmod.rfc7860
    - pysnmp.proto.secmod.rfc7860.auth
    - pysnmp.smi
    - pysnmp.smi.mibs
    - pysnmp.smi.mibs.instances
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://www.pysnmp.com/pysnmp
  license: BSD-2-Clause
  license_family: BSD
  license_file: LICENSE.rst
  summary: SNMP library for Python
  description: |
    PySNMP is a cross-platform, pure-Python SNMP engine implementation. It
    features fully-functional SNMP engine capable to act in Agent/Manager/Proxy
    roles, talking SNMP v1/v2c/v3 protocol versions over IPv4/IPv6 and other
    network transports.
  doc_url: https://docs.lextudio.com/pysnmp
  dev_url: https://github.com/lextudio/pysnmp

extra:
  recipe-maintainers:
    - nehaljwani
