{% set name = "pysnmp" %}
{% set version = "7.1.28" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://github.com/lextudio/{{ name }}/archive/refs/tags/v{{ version }}.tar.gz
  sha256: cf3c246761cadacf2824b7c35ad9c2db18e6b9c59ceb332ab2d4a205c69b023d

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv --no-build-isolation
  skip: true  # [py<310]

requirements:
  host:
    - pip
    - python
    - flit-core >=3.9.0
  run:
    - python
    - pyasn1 >=0.6.3

# Tests requiring external MIB preparation or network resources are excluded from the build environment.`
{% set ignore_tests = "--ignore=tests/smi/manager/test_mib-tree-inspection.py" %}
{% set ignore_tests = ignore_tests + " --ignore=tests/smi/test_if_mib_write.py" %}
{% set ignore_tests = ignore_tests + " --ignore=tests/hlapi/v1arch/asyncio/manager/cmdgen/test_v1arch_v2c_bulkwalk.py" %}
{% set ignore_tests = ignore_tests + " --ignore=tests/hlapi/v3arch/asyncio/manager/cmdgen/test_v2c_bulkwalk.py" %}
{% set ignore_tests = ignore_tests + " --ignore=tests/smi/manager/test_configure-mib-viewer-and-resolve-pdu-varbinds.py" %}
{% set ignore_tests = ignore_tests + " --ignore=tests/smi/manager/test_convert-between-pdu-varbinds-and-mib-objects.py" %}

# Tests relying on external resources or environment-sensitive SNMP behavior.
{% set deselect_tests = "--deselect=tests/hlapi/v1arch/asyncio/manager/cmdgen/test_v1arch_v1_get.py::test_v1_get_timeout_slow_object" %}
{% set deselect_tests = deselect_tests + " --deselect=tests/hlapi/v1arch/asyncio/manager/cmdgen/test_v1arch_v1_get.py::test_v1_get_dateandtime_object" %}
{% set deselect_tests = deselect_tests + " --deselect=tests/hlapi/v1arch/asyncio/manager/cmdgen/test_v1arch_v1_get.py::test_v1_get_physaddress_object" %}
{% set deselect_tests = deselect_tests + " --deselect=tests/hlapi/v1arch/asyncio/manager/cmdgen/test_v1arch_v1_get.py::test_v1_get_scaled_integer_object" %}
{% set deselect_tests = deselect_tests + " --deselect=tests/hlapi/v1arch/asyncio/manager/cmdgen/test_v1arch_v1_get.py::test_v1_get_scaled_unsigned_object" %}
{% set deselect_tests = deselect_tests + " --deselect=tests/hlapi/v1arch/asyncio/manager/cmdgen/test_v1arch_v1_get.py::test_v1_get_multiple_objects" %}
{% set deselect_tests = deselect_tests + " --deselect=tests/hlapi/v1arch/asyncio/manager/cmdgen/test_v1arch_v1_set.py::test_v1_set_mac_address" %}
{% set deselect_tests = deselect_tests + " --deselect=tests/hlapi/v1arch/asyncio/manager/cmdgen/test_v1arch_v1_set.py::test_v1_set_table_creation" %}
{% set deselect_tests = deselect_tests + " --deselect=tests/hlapi/v1arch/asyncio/manager/cmdgen/test_v1arch_v2c_bulk.py::test_v2c_bulk_multiple_input" %}
{% set deselect_tests = deselect_tests + " --deselect=tests/hlapi/v3arch/asyncio/manager/cmdgen/test_v1_get.py::test_v1_get_slow_object" %}
{% set deselect_tests = deselect_tests + " --deselect=tests/hlapi/v3arch/asyncio/manager/cmdgen/test_v1_set.py::test_v1_set_table_creation" %}
{% set deselect_tests = deselect_tests + " --deselect=tests/hlapi/v3arch/asyncio/manager/cmdgen/test_custom_asn1_mib_search_path.py::test_custom_asn1_mib_search_path" %}
{% set deselect_tests = deselect_tests + " --deselect=tests/hlapi/v1arch/asyncio/manager/cmdgen/test_v1arch_v2c_get.py::test_v2_get_no_access_object" %}
{% set deselect_tests = deselect_tests + " --deselect=tests/hlapi/v1arch/asyncio/manager/cmdgen/test_v1arch_v2c_get.py::test_v2_get_legacy_object" %}
{% set deselect_tests = deselect_tests + " --deselect=tests/hlapi/v3arch/asyncio/manager/cmdgen/test_v2c_get.py::test_v2_get_no_access_object" %}
{% set deselect_tests = deselect_tests + " --deselect=tests/hlapi/v3arch/asyncio/manager/cmdgen/test_v2c_get.py::test_v2_get_legacy_object" %}
{% set deselect_tests = deselect_tests + " --deselect=tests/hlapi/v3arch/asyncio/manager/cmdgen/test_v2c_bulk.py::test_v2c_bulk_non_exist" %}
{% set deselect_tests = deselect_tests + " --deselect=tests/hlapi/v1arch/asyncio/manager/cmdgen/test_v1arch_v1_walk.py::test_v1_walk" %}
{% set deselect_tests = deselect_tests + " --deselect=tests/hlapi/v3arch/asyncio/manager/cmdgen/test_v1_walk.py::test_v1_walk" %}
{% set deselect_tests = deselect_tests + " --deselect=tests/hlapi/v1arch/asyncio/manager/cmdgen/test_v1arch_v2_walk.py::test_v2_walk" %}
{% set deselect_tests = deselect_tests + " --deselect=tests/hlapi/v3arch/asyncio/manager/cmdgen/test_v2_walk.py::test_v2_walk" %}
{% set deselect_tests = deselect_tests + " --deselect=tests/hlapi/v3arch/asyncio/agent/ntforg/test_default-v1-trap.py::test_send_trap_custom_mib" %}
{% set deselect_tests = deselect_tests + " --deselect=tests/hlapi/v3arch/asyncio/agent/ntforg/test_v3-trap.py::test_send_v3_trap_notification" %}
{% set deselect_tests = deselect_tests + " --deselect=tests/hlapi/v3arch/asyncio/agent/ntforg/test_v3-trap.py::test_send_v3_trap_notification_none" %}
{% set deselect_tests = deselect_tests + " --deselect=tests/hlapi/v3arch/asyncio/agent/ntforg/test_v3-trap.py::test_send_v3_trap_notification_invalid_user" %}
{% set deselect_tests = deselect_tests + " --deselect=tests/proto/test_network_address.py::test_inet_address_ipv4_resolv" %}
{% set deselect_tests = deselect_tests + " --deselect=tests/proto/test_network_address.py::test_inet_address_ipv6_resolv" %}
{% set deselect_tests = deselect_tests + " --deselect=tests/proto/test_network_address.py::test_inet_address_roundtrip" %}

test:
  source_files:
    - tests
  imports:
    - pysnmp
    - pysnmp.carrier
    - pysnmp.carrier.asyncio
    - pysnmp.carrier.asyncio.dgram
    - pysnmp.entity
    - pysnmp.entity.rfc3413
    - pysnmp.hlapi.asyncio
    - pysnmp.proto
    - pysnmp.proto.acmod
    - pysnmp.proto.api
    - pysnmp.proto.mpmod
    - pysnmp.proto.proxy
    - pysnmp.proto.secmod
    - pysnmp.proto.secmod.eso
    - pysnmp.proto.secmod.eso.priv
    - pysnmp.proto.secmod.rfc3414
    - pysnmp.proto.secmod.rfc3414.auth
    - pysnmp.proto.secmod.rfc3414.priv
    - pysnmp.proto.secmod.rfc3826
    - pysnmp.proto.secmod.rfc3826.priv
    - pysnmp.proto.secmod.rfc7860
    - pysnmp.proto.secmod.rfc7860.auth
    - pysnmp.smi
    - pysnmp.smi.mibs
    - pysnmp.smi.mibs.instances
  commands:
    - pip check
    - python -m pytest -v tests {{ ignore_tests }} {{ deselect_tests }}
  requires:
    - pip
    - pytest
    - pytest-asyncio
    - pysmi >=2.0.0
    - cryptography >=44.0.1

about:
  home: https://www.pysnmp.com/pysnmp
  license: BSD-2-Clause
  license_family: BSD
  license_file: LICENSE.rst
  summary: SNMP library for Python
  description: |
    PySNMP is a cross-platform, pure-Python SNMP engine implementation. It
    features fully-functional SNMP engine capable to act in Agent/Manager/Proxy
    roles, talking SNMP v1/v2c/v3 protocol versions over IPv4/IPv6 and other
    network transports.
  doc_url: https://docs.lextudio.com/pysnmp
  dev_url: https://github.com/lextudio/pysnmp

extra:
  recipe-maintainers:
    - nehaljwani
