travis:
  secure:
    BINSTAR_TOKEN: cDqS7RNG9dbZ+mpdaXJ8Ni+Z3NFr/aMIhR73lyq8v/DdCuefGEC9e1f5ANow2GiiLygIOIgoIQ7jhxYCHhN8xlxPZu9jWVYWEkFnWua1h27ZxIMidwjFs/jGn4m03yYpszf6NdS6toylu+rcY7BrB3ar5OW1AOm+xxhSNJzD3MVSxTeyA0iCYujgmi3OFvjgk+ntelpuQR/mYbRYxp2jV233vujV1qzs+6GCNbaxlKObPbZKj4wMzt9mB1b/cTTe7xng7ekYl6ghW0jeYIOyMSvgGhhbSEbkxUIYg0g0sEpQkfaVKcvPTLB2YrSfmoQOBdW+q/HUwkLLPDILa6ex/zcVNoOh6EXsjsCoe2BqPv3Tv0LKtVYpv3Q8GwFA2hvj0ujI33OyKg1Rrw3b8HvC8aF6s97SwfbqA3r+S28Zk+pxf1H4nhN2WTDl7L4GMAS0WnZbwN5QTTvARl7J8dsW9YSrZN/qCCgjx6aJXgJZl/vq4bXTyGeGHaBBmZ476MtgHF5Bf8m6wxFd9xOKDyKhCyRQ48TEOR7fWuvt2idluvhDEWFXXRA/4mr5yuHXtIgZCW6iXR7l6jvE4+R7C3wPe2gphpYhuxe/K6jVVZp0dsKO4A/GMv8Kf/5RA3PVrqGWXVvFis4hI1BzjpcJo7EDLjajKJTcfR0p1teYUtsHzGs=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
