travis:
  secure:
    BINSTAR_TOKEN: A8Np9bmkQ5oQ8sF7rYsEgAxXj8peFpmmlkrp0mwXNTPnLPB/hNxK8u5ajXEOoXibp6qf06PmfGJH7tCBAyjElINKJXTwWowR+PrOc2d7agxcSF5BNd+DMnyuKRJks+uF8RAmqk8D2r7hGpT/uyvoAr+LVsgLThz5MdA10SKl7ZwgKiDCcWyPHFu8KFTb1bc6NAergJyFkN6NQZVzUmeWrCz2g7MTgSKQ9UWCC1Fz1T/kMcEsvooSH633GVoWH2XJFgu92EhCSLd+pFda6gO6XYA8scFbS6+IDgbLYLTolozsl9yI3irP2G9m5NhjL0uskghHyp4P03YWrdNTZ1GgRb13t2ho1z677covUhd7dbuWqtWX4hTgV86oDaEcftzlEyd1k+65+gyJNRmmR/TTZRVe5hhy6aciBQFYk/QlwlqN/mwgmxlW7AAafUWaht9TyDUL/VaUD5V6fZJMMagWm46cSwqWL9ncbZvHdh4KohPJRu/w0DTDgpri/J4kNIlw9x5s+b4/HdcLaz1jvNfH4VumXA1+On/YCU/c0q7sq8Pj5nrJSiHxuNfW8sYq2buaD8igz1z2wNnul/p2HbJ/ffl6oouFKpzJJJX6U5DXuSrRlsEqZvLp2LYSE40VR6/tsJ6Dacit1nc+40RiJqk7fdQSZ3WhAAo59A0FzegHlt0=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
